language: android

sudo: false

jdk:
  - oraclejdk8

android:
  components:
    # Use the latest revision of Android SDK Tools
    - platform-tools
    - tools

    # The BuildTools version used by your project
    - build-tools-25.0.0

    # The SDK version used to compile your project
    - android-25

    # Additional components
    - extra
    - addon

before_script:
  - git clone --depth 1 https://github.com/urho3d/android-ndk.git
  - export ANDROID_NDK_HOME=$(pwd)/android-ndk
  - wget https://github.com/opencv/opencv/releases/download/3.1.0/OpenCV-3.1.0-android-sdk.zip
  - unzip OpenCV-3.1.0-android-sdk.zip
  - export OPENCV_ANDROID_SDK=$(pwd)/OpenCV-android-sdk

script:
  ./gradlew build
